### PR TITLE
floats: use more efficient "is sorted" routine

### PR DESCRIPTION
**Pull request by jbduncan**
This PR introduces a modernization change that is not necessarily related to #617 but which was spun out from my attempts at generifying the leaves of `graph`. Benchmarks to follow.

Blocked by https://github.com/gonum/gonum/pull/1940.

### CODE REVIEW

**Comment by jbduncan** [comment]
Unexpectedly, there are no benchmarks that exercise `floats.Within` directly or indirectly, and the only other code change affects a test, so there's nothing to run here.

**Comment by kortschak** [comment]
This needs to pick up the changes in master.

**Comment by jbduncan** [comment]
> This needs to pick up the changes in master.

Done.

**Review by kortschak — COMMENTED** [review]
Any appeal to efficiency needs to be supported by benchmarks.

**Comment by jbduncan** [comment]
@kortschak Thanks for challenging me on this. On re-reading the source code, I see that `sort.Float64sAreSorted` delegates to `slices.IsSorted`, so if there is any improvement, it would be so small that I don't think this PR is worth it anymore.

Closing.

**Pull request closed without merging**
