### PR TITLE
gonum: add initial vgo support

### PR DESCRIPTION
**Pull request by sbinet**
Please take a look.

### CODE REVIEW

**Comment by kortschak** [comment]
Is there some testing of `vgo` with this `go.mod` that you can add that makes sure it's working correctly?

**Comment by sbinet** [comment]
I've added some tentative code that verifies the vgo module deps.
but for a complete test, I suppose one would need to test with *clients* of `gonum.org/v1/gonum` :)

**Comment by sbinet** [comment]
arf... `vgo` can only be compiled with Go >= 1.10.x...

**Comment by kortschak** [comment]
Can the tests not be put in a script that runs them conditionally on `$(go version)`?

**Comment by sbinet** [comment]
Sure. Would be easier to have them written directly in Go and put in the 'tools' repo :)

**Comment by kortschak** [comment]
In this case I'm not sure it would, but maybe.

**Comment by sbinet** [comment]
I'd be tempted to remove (for now) the `vgo` test and only enable them when `Go-1.11` hits the door.
having a `go.mod` file now will allow people living with `go-1.9.x`, `go-1.10.x` and `master` to experiment and play with `vgo`.

what do you think?

**Comment by kortschak** [comment]
SGTM

**Comment by sbinet** [comment]
updated with latest `vgo`:
```
$> vgo version
go version devel +b3562658fd Sun Jun 10 17:04:22 2018 +0000 linux/amd64 vgo:2018-02-20.1
```

**Comment by sbinet** [comment]
PTAL

**Comment by kortschak** [comment]
I take it the netlib dep is due to the cblas test flag. Will this force users to pull that? Maybe edit that line out.

**Comment by sbinet** [comment]
done.

**Pull request merged**
