### PR TITLE
Unexport Panics testing helper. It was exported unnecessarily.

### LINKED ISSUE #246: stat: testing helper Panics is exported unnecesarily
The [`Panics` test helper is exported](https://github.com/gonum/gonum/blob/84c9c3a316a0fb7edb4aaa219024a55304f19dd0/stat/stat_test.go#L954-L964). It is only used in package stat and so this is unnecessary.

### PR DESCRIPTION
**Pull request by danielfireman**
Fixes  #246.

### CODE REVIEW

**Comment by kortschak** [comment]
Can you please also add yourself to A+C.

**Comment by danielfireman** [comment]
Done.

**Comment by kortschak** [comment]
Thank you

**Comment by danielfireman** [comment]
Sure! Glad to help!

**Pull request merged**
