### PR TITLE
Fixed a grammatical error in Unit docs

### PR DESCRIPTION
**Pull request by llamington**
Fixed a grammatical from "a run time" to "at run time"

Please take a look.

### CODE REVIEW

**Comment by vladimir-ch** [comment]
Thanks. Can you send another PR with the commit message "A+C: add Bailey Lissington", adding yourself to AUTHORS and CONTRIBUTORS? When that's done, I'll merge this.

**Comment by kortschak** [comment]
@llamington The second commit should be in a separate PR. We will need to fix up the commit message for the first commit and we cannot do this with the GitHub UI when there is more than one commit. Can you either edit the commit history to make the commit message for the first commit be "unit: fix typo in package doc comment" or revert the second commit so that we can do the fixup in a squash.

**Comment by llamington** [comment]
All sorted

**Review by kortschak — APPROVED** [review]
Thanks

**Pull request merged**
