### PR TITLE
DOC: fix typo in documentation for `Row` method

### PR DESCRIPTION
**Pull request by sglyon**

### CODE REVIEW

**Comment by sglyon** [comment]
Done!

I also  edited the commit message of the original commit in this PR to reflect your comment.

Thanks

**Comment by btracey** [comment]
@kortschak I'm not sure what our policy is with using the "Dismiss review" button before changes like this. Do we have a strict policy, or just "better judgement"? Basically, not sure if I should dismiss review and submit, or wait for you to give explicit approval.

**Comment by Kunde21** [comment]
@btracey I'm treating the changes as needing requester approval or approval from 2 other reviewers.

**Comment by Kunde21** [comment]
Thank you @sglyon

**Comment by kortschak** [comment]
I think "use judgement", in this case the request is obvious and any approver would be OK. In other cases the request may be more subtle.

**Comment by btracey** [comment]
Great, I agree.

**Pull request merged**
