### PR TITLE
spatial/r3: rework test for RotationFromQuat

### PR DESCRIPTION
**Pull request by vladimir-ch**
Please take a look.

### CODE REVIEW

**Comment by vladimir-ch** [comment]
I test via `Rotation.Rotate` applied on a random point instead of `Rotation.Matrix` because the latter uses the same formula as `RotationFromQuat` and so could be considered not independent enough.

Working on the test I discovered `Rotation.Matrix` which does the same thing as `Mat.RotationFromQuat`. Shouldn't only one of them exist?

**Comment by kortschak** [comment]
My original intention was to not convert to a matrix. I forgot about `Rotation`. I think that the `Rotation.Matrix` code could return a `Mat` and have `RotationFromQuat` go away, maybe adding a `Mat` method that returns the type in its concrete form.

**Review by kortschak — APPROVED** [review]
LGTM, but I agree some of this API should go away; we now have two trivially different ways to do the same thing.

**Comment by kortschak** [comment]
I'll have an API reduction ready soon.

**Comment by vladimir-ch** [comment]
Good to know, I've just been looking at it too :-)

**Pull request merged**
