### PR TITLE
ci: back up on version specification

### PR DESCRIPTION
**Pull request by kortschak**
The released action is now v1.2.0, so v1, should be enough to specify the correct version.

Please take a look.

### CODE REVIEW

**Comment by kortschak** [comment]
Since this is not going to make the situation worse, but may fix the missing base report issue, I am going to merge this.

TBR

**Comment by kortschak** [comment]
:frowning_face:

**Review by vladimir-ch — COMMENTED** [review]
LGTM

**Comment by kortschak** [comment]
Codecov are sending a PR to the action that should fix this.

**Comment by kortschak** [comment]
:tada:

**Pull request merged**
