### PR TITLE
travis: make sure checks exit non-zero if they fail

### PR DESCRIPTION
**Pull request by kortschak**
At the moment, it's printing file names for missing headers, but not failing.

Please take a look.

### CODE REVIEW

**Comment by kortschak** [comment]
This doesn't fix the problem, and I don't understand now 1. why it doesn't work as it is in master and 2. why this doesn't work either.

**Comment by sbinet** [comment]
wouldn't this because the `run-parts` script has no `set -e` line?

**Comment by kortschak** [comment]
Could be, except that the tests are run by `run-parts` and they successfully fail when needed.

**Comment by kortschak** [comment]
I think you are right. The tests are last and so would be returned.

**Comment by kortschak** [comment]
PTAL (experimentally confirmed)

**Comment by kortschak** [comment]
I don't understand these failures. They are replicable on my machine locally, but have never appeared before. I will look into what is going on.

**Comment by kortschak** [comment]
OK. I now understand. The tests previously were passing exactly because of the loop here quietening the failures. I never saw the failures that we have above because I generally don't run `-tags=noasm` locally. The issue comes down now to numerical stability of ED used in `mds.Torgerson`, which is something that we've already seen.

**Comment by kortschak** [comment]
I've rebased this to ensure that it now passes and changed the commit message since the fix was more general than previously though.

PTAL

**Pull request merged**
