### PR TITLE
r3.Vec as [3]float64

### PR DESCRIPTION
**Pull request by sbinet**
Please take a look.

### CODE REVIEW

**Comment by egonelbre** [comment]
How does this affect performance?

Small arrays can be significantly slower: https://github.com/egonelbre/exp/blob/master/bench/vector_fusing/vector_test.go

```
# array
BenchmarkAddMul-32                      70589480                17.3 ns/op
# struct
BenchmarkStructAddMul-32                1000000000               0.740 ns/op
```

**Comment by sbinet** [comment]
hum... that's unfortunate.
do you know the underlying reason for this? (it doesn't seem to be bounds-check0

**Comment by egonelbre** [comment]
SSA doesn't handle arrays nicely, see https://github.com/golang/go/issues/15925 for more information.

**Comment by kortschak** [comment]
I'd really rather this didn't happen. It breaks symmetry with r1 and r2, and if symmetry were retained , would break nice ergonomics (that I believe has been discussed elsewhere, but can't find) in allowing direct `r2.Point` interconversion to `vg.Point`.

I'm happy for additional operators to be added, though the API should be discussed first.

**Comment by sbinet** [comment]
the `struct{x,y,z} -> [3]float64` was discussed in the issue #1049.

as the SSA issue seem a bit over my head (and been lingering for a couple of years, now) I suspect changing to an array is out of question (x20 in performances is not something we want to leave on the table)

I'll start a discussion on `gonum-dev`.

**Pull request closed without merging**
