### PR TITLE
graph/formats/dot: rename Kind* => *Kind

### LINKED ISSUE #24: travis: check code generation for dot parser in graph/formats/dot/internal
This requires that gocc and make be installed on the builder (and possibly other things that may not be present).

### LINKED ISSUE #115: graph/formats/dot/ast: rename Kind* to *Kind
This reflects the Gonum convention that labels be readable as English phrases or sentences.

### PR DESCRIPTION
**Pull request by kortschak**
Added code generation check to ensure the correct changes are happening.

Due to changes in gocc, code needed to be regenerated to pass. I'm not sure I like this.

Closes #24.
Closes #115.

### CODE REVIEW

**Comment by mewmew** [comment]
> Due to changes in gocc, code needed to be regenerated to pass. I'm not sure I like this.

Could you elaborate? This may be due to a recent change by @awalterschulze or I. Perhaps https://github.com/goccmack/gocc/pull/49?

**Comment by kortschak** [comment]
I am not sure of the reason for the changes, but there were seemingly unnecessary whitespace changes in the generated code. You can see this in the diffs. I don't like that builds may fail due to effects at a distance when checking code gen. Probably we should pin the gocc version when we check, but gocc doesn't use anything that looks like versioning yet.

I'm also wondering about inclusion of formatted-out print statements inthe generated code, and the use of `this` receiver names.

**Comment by awalterschulze** [comment]
It looks like a lot of the gofmt changes, those should be stable now.

`this` could be changed with a pull request to gocc.

Pinning the version of projects in go is currently mostly done using the git hash and vendoring, but its a real debatable topic whether a code generator should be vendored.   So I will probably not give any further opinions on that.

**Comment by mewmew** [comment]
> I am not sure of the reason for the changes, but there were seemingly unnecessary whitespace changes in the generated code.

The original issue was that gocc could output code which did not conform to gofmt formatting (https://github.com/goccmack/gocc/issues/36). To resolve this issue, a lot of whitespace changes were made in the generated output (as seen in PR https://github.com/goccmack/gocc/pull/49).

Specifically for graph/formats/dot the changes are as follows.

Removal of unnecessary whitespace.
* graph/formats/dot/internal/lexer/lexer.go
* graph/formats/dot/internal/lexer/transitiontable.go
* graph/formats/dot/internal/parser/actiontable.go
* graph/formats/dot/internal/parser/gototable.go

Whitespace changes to conform with gofmt.
* graph/formats/dot/internal/parser/parser.go

Introduction of unnecessary whitespace (NOTE: this is a regression, and the whitespace should not have been introduced).
* [graph/formats/dot/internal/lexer/lexer.go](https://github.com/gonum/gonum/pull/139/files#diff-c5af652891f7f8f775146efd635cb3b8R147)

I'll look into the regression highlighted above. Other than that the output should be more stable now, as gocc includes a regression test as well, added by @awalterschulze, to ensure that the generated output passes gofmt.

The use of `this` as a receiver name is mostly due to legacy I would guess. As already noted by Walter, a pull request could easily change the use of *this* to something more Go-idiomatic; https://github.com/golang/go/wiki/CodeReviewComments#receiver-names

**Comment by mewmew** [comment]
The identified regression should be fixed by https://github.com/goccmack/gocc/pull/51

**Comment by mewmew** [comment]
> The identified regression should be fixed by goccmack/gocc#51

The regression has been fixed, and a PR has been submitted to gonum/graph (https://github.com/gonum/gonum/pull/147) which simplifies the Makefile for regenerating the parser of graph/formats/dot, now that Gocc outputs Go source code which conforms to gofmt formatting.

**Comment by kortschak** [comment]
I can probably find some time tomorrow to send a PR for the receiver naming, and I'll add a script to pin to a specific hash for the gocc pull in the CI.

**Comment by mewmew** [comment]
> I can probably find some time tomorrow to send a PR for the receiver naming, and I'll add a script to pin to a specific hash for the gocc pull in the CI.

Lovely to hear!

**Pull request merged**
