### PR TITLE
stat: panic when calling CDF or Quantile with empty x

### PR DESCRIPTION
**Pull request by kortschak**
Please take a look.

### CODE REVIEW

**Review by sbinet — APPROVED** [review]

**Comment by romanwerpachowski** [comment]
Not sure about it. It makes no sense to calculate a quantile for an empty array. Panicking seems to be the right behaviour. Returning zero can lead to hard to detect bugs in user code.

**Comment by kortschak** [comment]
R returns NULL, which we obviously can't do. This is related to the discussion @vladimir-ch and I had in https://github.com/gonum/gonum/pull/1622#discussion_r628281871 where we came to the same conclusion. The rationale for zero was that any quantile between infinities is 0, but NaN and panic are also reasonable. For consistency with #1622 and following the same rationale I'd be happy to make an explicit panic here and document that it panics, retaining the tests.

**Comment by romanwerpachowski** [comment]
>  I'd be happy to make an explicit panic here and document that it panics,
retaining the tests

I'd vote for that.

**Comment by kortschak** [comment]
`CDF` should also probably panic with empty input and does with the same currently uninformative message. I'll do that too.

**Comment by kortschak** [comment]
PTAL

**Review by romanwerpachowski — APPROVED** [review]
I suggest renaming the PR now :)

**Comment by kortschak** [comment]
Done (I had remembered at the beginning, but not the end — I did notice that the branch name was agnostic, which made me happy at the time, and then I moved on).

**Pull request merged**
