### PR TITLE
stat/sampleuv: add missing return

### PR DESCRIPTION
**Pull request by kortschak**
@btracey Please take a look.

### CODE REVIEW

**Comment by btracey** [comment]
Can be fixed in a different PR

**Comment by kortschak** [comment]
Perm is linear - it's a single swapping sweep over n elements.

**Comment by btracey** [comment]
Now that you mention it, I'm sure you've pointed this out to me before. Sorry.

**Comment by kortschak** [comment]
The alternative algorithm is worse than O(n^2) though, it looks like O(n^2 log n) to me (n = |idxs|) because of the sort.

**Pull request merged**
