### PR TITLE
add TODOs badge to "Issues" section of README

### LINKED ISSUE #1274: README: add TODOs Badge
Hi there! I wanted to propose adding the following badge to the README to indicate how many `TODO` comments are in this codebase:

[TODOs](https://www.tickgit.com/browse?repo=github.com/gonum/gonum)

The badge links to `tickgit.com` which is a free service that indexes and displays TODO comments in public github repos. It can help surface latent work and be a way for contributors to find areas of code to improve, that might not be otherwise documented.

The markdown is:

```
[![TODOs](https://badgen.net/https/api.tickgit.com/badgen/github.com/gonum/gonum)](https://www.tickgit.com/browse?repo=github.com/gonum/gonum)
```

Thanks for considering, feel free to close this issue if it's not appropriate or you prefer not to!

(full disclosure, I am the creator/maintainer of `tickgit`)

### PR DESCRIPTION
**Pull request by patrickdevivo**
closes #1274

Seeing how the badge looks next to the "Issues" heading

### CODE REVIEW

**Comment by kortschak** [comment]
I think this looks OK, but I'd like to wait for others.

**Comment by kortschak** [comment]
@patrickdevivo Can you send a PR with a commit message "A+C: add Patrick DeVivo", adding yourself to the AUTHORS and CONTRIBUTORS files. Then we can merge both of these. Thanks

**Comment by kortschak** [comment]
Ah, sorry, can you amend the first commit to be "README: add TODOs badge" and remove the reference to the issue.

**Comment by patrickdevivo** [comment]
done! how does it look now?

**Pull request merged**
