### PR TITLE
add Ch. Meessen to AUTHORS and CONTRIBUTORS

### PR DESCRIPTION
**Pull request by chmike**
Please take a look.

### CODE REVIEW

**Comment by sbinet** [comment]
needed by https://github.com/gonum/plot/pull/498

**Comment by kortschak** [comment]
It would have been fine to amends and force push here, but I'll approve the other.

**Comment by chmike** [comment]
Sorry. I have the habit to not amend pushed commits. I wasn't sure of the effect on the PR. I never did it before.

**Comment by kortschak** [comment]
On PR branches it's fine. We have protection on the master branch, so we won't break people.

**Pull request closed without merging**
