### PR TITLE
all: fix doc comments

### PR DESCRIPTION
**Pull request by knowmost**
fix doc comments 

The A+C PR: https://github.com/gonum/gonum/pull/1976

### CODE REVIEW

**Comment by kortschak** [comment]
This looks similar to the PR by @largemouth. Both have "I may be slow to respond." and private history, and both ignored the PR contributor instructions.

**Review by kortschak — COMMENTED** [review]
Please remove the signed-off-by in both PRs.

**Review by kortschak — APPROVED** [review]
@knowmost Thanks. Sorry, small PRs with the signs above can be more trouble than they are worth. This is clearly not the case this time since you have responded quickly and have already prepared the A+C change.

This LGTM.

**Comment by kortschak** [comment]
> I found that CI failed. Do I need to do anything? If have please feel free to tell me.

No, the issue is fixed by #1962. Recently GH moved there MacOS builders to apple silicon and so we are picking up floating point differences that we were missing previously. Once that PR is merged, this will pass.

**Review by vladimir-ch — APPROVED** [review]

**Comment by kortschak** [comment]
@knowmost Please rebase your PRs onto the new master.

**Comment by kortschak** [comment]
Please rebase rather than merge.

**Comment by kortschak** [comment]
That should not have caused this to close.

**Pull request closed without merging**
