### PR TITLE
ci: update testing for go1.13

### PR DESCRIPTION
**Pull request by kortschak**
Please take a look.

### CODE REVIEW

**Comment by kortschak** [comment]
Those declarations are still weird. I will leave it.

**Comment by kortschak** [comment]
For clarity, the go version directive will change if we introduce language feature uses above go1.12 since this is what it's for. How this interacts with multiple version support is still something that has not been properly clarified by the Go team.

**Comment by chewxy** [comment]
shouldn't the go version be switched to 1.13 given 1.13 is the first official version to support modules

**Comment by kortschak** [comment]
Go1.11 does with the experiment turned on, which is how we use them. When there is no requirement for `GO111MODULES`, then I suppose we should update the version directive.

**Pull request merged**
