### PR TITLE
A+C: Add employer to AUTHORS

### PR DESCRIPTION
**Pull request by romanwerpachowski**
Please take a look.

### CODE REVIEW

**Review by sbinet — APPROVED** [review]

**Review by kortschak — COMMENTED** [review]
s/Add/add/ in squash please.

Is this for future commits or has this already been true?

**Comment by romanwerpachowski** [comment]
Future commits.

**Comment by kortschak** [comment]
Can we wait until they go in. I'm happy to approve for then.

**Comment by kortschak** [comment]
@romanwerpachowski This can be close now with #1570 having been merged.

**Pull request closed without merging**
