### PR TITLE
stat/all: Change all Source to Src

### PR DESCRIPTION
**Pull request by btracey**
Fixes original gonum/stat #147

### CODE REVIEW

**Comment by btracey** [comment]
In the commit message you mean?

**Comment by kortschak** [comment]
Yes, that's right. Now I'm confused about why there are two commits. Sorry.

**Comment by sbinet** [comment]
(you should probably squash the 2 commits into 1, though)

**Comment by btracey** [comment]
I'm also confuled about the two commits. But, squashing.

**Pull request merged**
