### PR TITLE
Update go.mod with go mod -sync

### PR DESCRIPTION
**Pull request by ChrisHines**

### CODE REVIEW

**Comment by kortschak** [comment]
Is it the case that the go mod tooling is unaware of tags and testing? I don't really want netlib to be marked as a dependency; it's not unless it's chosen to be.

**Comment by ChrisHines** [comment]
I don't know. I'm still trying to get the issue described in https://github.com/gonum/gonum/issues/548 to work. Fixing the import path was only part of the problem.

At this point the go.mod file in the gonum/plot repo is referencing an old version of gonum/gonum with the bad import statement before your fix. My approach to updating the go.mod file is to change the version in go.mod to `latest` and run `go mod -sync`. Maybe that's too aggressive at this stage of the module tooling, but when I do that in the gonum/plot repo then netlib gets added with an `// indirect` dependency. So that led me to the idea that the gonum/gonum/go.mod file needed `go mod -sync` to declare all its dependencies.

I defer to your decision as a maintainer. Feel free to close this PR if it's not valid.

**Comment by kortschak** [comment]
You've peaked my interest and now I'm trying to get the the `go mod` command to work - without success; I just get "go mod: cannot use outside module". I guess I'm holding it wrong.

**Comment by ChrisHines** [comment]
Are you getting that on the gonum/plot repo or this repo? I've found an obsolete import statement in gonum/plot that causes some problems: https://github.com/gonum/plot/blob/master/palette/moreland/luminance_test.go#L13

**Comment by kortschak** [comment]
In gonum/gonum and gonum/plot (using `go version devel +c2ba0ca`).

**Comment by ChrisHines** [comment]
That's the error I get if I try to use go mod inside GOPATH without setting the environment variable GO111MODULE=on.

**Comment by kortschak** [comment]
Yeah, I saw that on golang-nuts just before. Thanks.

**Comment by kortschak** [comment]
In the absence of clear use documentation in the go mod help, I fell back on tried and true unix approaches. I hand edited the go.mod for gonum/plot, removing the gonum/gonum line, and then re-ran go mod -sync. This fixed the problem.

**Comment by kortschak** [comment]
I have sent a PR to gonum/plot that should fix the problem, gonum/plot#458. Please try it out.

**Comment by ChrisHines** [comment]
It works. Thanks.

**Pull request closed without merging**
