### PR TITLE
lapack: add Dlag2 subroutine

### PR DESCRIPTION
**Pull request by soypat**
ARE issue #1651

### CODE REVIEW

**Comment by soypat** [comment]
_ping_

**Comment by vladimir-ch** [comment]
Let's first get Dorgr2 done, only little left to do there.

**Comment by kortschak** [comment]
Given the limited bandwidth available for review, the optimal approach to ordering work in a complex addition like this is a strict dependency ordering, only moving on to dependent packages once dependencies have been accepted and merged; this reduces the overall cognitive load on reviewers since it ceases to be necessary to hold more than one package in mind at a time. Having too many things in the air will hamper progress rather than help it.

**Comment by soypat** [comment]
> Having too many things in the air will hamper progress rather than help it.

This has started to become painfully apparent. 

> the optimal approach to ordering work in a complex addition like this is a strict dependency ordering

Sounds good. A slow but methodical and precise approach.

**Comment by soypat** [comment]
closed due to branch mismanagement.

**Pull request closed without merging**
