### PR TITLE
Update the version of netlib.

### PR DESCRIPTION
**Pull request by dlorenc**
These two packages have a circular dependency on each other at old versions
This is making it hard to update the dependencies of packages further upstream. I
hope this helps, and this is an OK bump!

### CODE REVIEW

**Comment by dlorenc** [comment]
Ref https://github.com/gonum/netlib/pull/80

**Comment by kortschak** [comment]
Thanks for sending the change. Can you show me what problem is caused by this? I've just tried locally to see what happens, and I can't get a failure.

```
~ $ mkdir foo
~ $ cd foo
~/foo $ go mod init foo
go: creating new go.mod: module foo
~/foo $ go get gonum.org/v1/gonum@latest
go: gonum.org/v1/gonum latest => v0.8.2
~/foo $ cat go.mod
module foo

go 1.15

require gonum.org/v1/gonum v0.8.2 // indirect
~/foo $ cat version.go 
package main

import (
	"fmt"

	"gonum.org/v1/gonum"
)

func main() {
	fmt.Println(gonum.Version())
}
~/foo $ go build ./version.go 
~/foo $ go mod tidy
~/foo $ cat go.mod 
module foo

go 1.15

require gonum.org/v1/gonum v0.8.2
~/foo $ ./version 
v0.8.2 h1:CCXrcPKiGGotvnN6jfUsKk4rRqm7q09/YbKb5xCEvtM=
~/foo $ cat version.go 
package main

import (
	"fmt"

	"gonum.org/v1/gonum"
	"gonum.org/v1/gonum/blas/blas64"
	"gonum.org/v1/gonum/mat"
	"gonum.org/v1/netlib/blas/netlib"
)

func main() {
	fmt.Println(gonum.Version())

	blas64.Use(netlib.Implementation{})

	m := mat.NewDense(3, 3, []float64{
		3, 3, 3,
		3, 3, 3,
		3, 3, 3,
	})
	m.Mul(m, m)

	fmt.Println(mat.Formatted(m))
}
~/foo $ CGO_LDFLAGS="-L/usr/local/lib -lopenblas" go build ./version.go 
~/foo $ go mod tidy
~/foo $ cat go.mod 
module foo

go 1.15

require (
	gonum.org/v1/gonum v0.8.2
	gonum.org/v1/netlib v0.0.0-20190313105609-8cb42192e0e0
)
~/foo $ ./version 
v0.8.2 h1:CCXrcPKiGGotvnN6jfUsKk4rRqm7q09/YbKb5xCEvtM=
⎡27  27  27⎤
⎢27  27  27⎥
⎣27  27  27⎦
```

This was with or without Gonum packages in my module download cache.

**Comment by kortschak** [comment]
@dlorenc Is this still an issue?

**Comment by dlorenc** [comment]
Closing for now. I can't tell if this is still an issue or not, ran into some other dependency issues trying to update...

Sorry! Thanks for your help.

**Pull request closed without merging**
