### PR TITLE
R2 vec api

### PR DESCRIPTION
**Pull request by sbinet**
Please take a look.

### CODE REVIEW

**Comment by sbinet** [comment]
same PR than #1298 (but for `r2.Vec`)

**Comment by kortschak** [comment]
Ugh, this identified an issue with the approach I'm taking for doing the linting checks; it cannot extend the git history when the PR comes from another user's repo.

I'll look into it.

**Comment by kortschak** [comment]
The issue here is `git fetch --shallow-exclude=master origin r2-vec-api` uses `origin` and it should determine the repo from Travis variables (I hope this is possible). It's not.

If you send a PR that outputs the result of `git remote` during a Travis build, what is that output? I think this is the only possible way to get this information.

**Comment by kortschak** [comment]
Can you rebase this on to master please.

**Comment by sbinet** [comment]
done.

**Pull request merged**
