### PR TITLE
A+C: Add Fabian Wickborn

### PR DESCRIPTION
**Pull request by fawick**
As requested by @sbinet in https://github.com/gonum/plot/pull/415#issuecomment-747400180.

### CODE REVIEW

**Comment by kortschak** [comment]
lc "Add" in commit message, but otherwise LGTM.

**Comment by fawick** [comment]
ICYMI I did s/Add/add/

**Review by kortschak — APPROVED** [review]
Waiting for merge of gonum/plot#415.

**Comment by kortschak** [comment]
Thank you for your patience and apologies for the extremely long delay.

**Pull request merged**
