### PR TITLE
Add format for complex matrix

### PR DESCRIPTION
**Pull request by acheron2302**
This change add CFormatted function for mat package. It is like Formatted function but for complex matrix.
Note: Haven't support for python format and matlab format

### CODE REVIEW

**Comment by kortschak** [comment]
It seems to me that the best way to do this, given that we can't shoe horn complex matrices into the same infrastructure that we have for reals, would be to just copy the whole file and adjust it for complex values. This would leave only minor edits for the documentation and would ensure that the behaviour is consistent. It's not entirely clear to me why you stripped the documentation and other comments.

**Comment by acheron2302** [comment]
> It seems to me that the best way to do this, given that we can't shoe horn complex matrices into the same infrastructure that we have for reals, would be to just copy the whole file and adjust it for complex values. This would leave only minor edits for the documentation and would ensure that the behaviour is consistent. It's not entirely clear to me why you stripped the documentation and other comments.

wait i didn't modify anything excpet adding cformat.go and cformat_test.go

**Comment by kortschak** [comment]
Please just start from the complete copy and delete/modify as needed.

**Comment by kortschak** [comment]
Although it is worth spending some time to see if we can get away with less code duplication. That will not be trivial.

**Comment by vladimir-ch** [comment]
I'm closing this PR because it has gone stale. We're still interested in contributions, so please create a new PR if you still intend to submit this change.

**Pull request closed without merging**
