### PR TITLE
mat: generalise vector mul fast path

### PR DESCRIPTION
**Pull request by kortschak**
Please take a look.

### CODE REVIEW

**Comment by kortschak** [comment]
I'll wait also for @btracey since I've removed the `*VecDense` special case. This reduced some near exact code repetition but will make that type a tiny smidge slower.

**Comment by btracey** [comment]
I think instead of this we want to be using `untransposeExtract` a la https://github.com/gonum/gonum/pull/932 . The main idea being that there are a lot of `Raw` types that don't conform to the assumptions of our Dense types (negative strides, Diag representations, etc.). `untransposeExtract` allows us to switch over the Dense types while also allowing external representations that implement the `RawFoo` types

**Comment by kortschak** [comment]
Do you want to send that?

**Comment by kortschak** [comment]
GitHub should have closed this, but Closes comments don't seem to work except in the first comment.

**Pull request closed without merging**
