### PR TITLE
all: add canonical imports

### PR DESCRIPTION
**Pull request by kortschak**
@btracey Please take a look.

Done with a combination of Go and bash.

`package.go`
```
package main

import (
	"fmt"
	"go/parser"
	"go/token"
	"os"
	"strings"
)

func main() {
	fset := token.NewFileSet()
	pkgs, err := parser.ParseDir(fset, os.Args[1], nil, parser.ParseComments)
	if err != nil {
		panic(err)
	}
	for p, pkg := range pkgs {
		if p == "main" {
			continue
		}
		for name, f := range pkg.Files {
			if f.Doc != nil {
				for _, c := range f.Doc.List {
					if strings.Contains(c.Text, "Package "+p) {
						fmt.Println(name)
						os.Exit(0)
					}
				}
			}
		}
	}
	os.Exit(1)
}
```

and in `GOPATH/src`

```
for d in $(find gonum.org/v1/gonum -not -path '*/\.*' -type d); do
    if f=$(go run package.go $d 2>/dev/null); then
        sed -i "s|^\(package .*\)$|\1 // import \"$d\"|" $f
    fi
done
```

### CODE REVIEW

**Comment by kortschak** [comment]
The following files are missed

```
gonum.org/v1/gonum
gonum.org/v1/gonum/blas/native/internal
gonum.org/v1/gonum/blas/testblas/benchautogen
gonum.org/v1/gonum/diff
gonum.org/v1/gonum/graph/encoding
gonum.org/v1/gonum/graph/ex
gonum.org/v1/gonum/graph/ex/fdpclust
gonum.org/v1/gonum/graph/formats
gonum.org/v1/gonum/graph/formats/dot/internal
gonum.org/v1/gonum/graph/formats/dot/internal/errors
gonum.org/v1/gonum/graph/formats/dot/internal/lexer
gonum.org/v1/gonum/graph/formats/dot/internal/lexer/testdata
gonum.org/v1/gonum/graph/formats/dot/internal/parser
gonum.org/v1/gonum/graph/formats/dot/internal/testdata
gonum.org/v1/gonum/graph/formats/dot/internal/token
gonum.org/v1/gonum/graph/formats/dot/internal/util
gonum.org/v1/gonum/graph/formats/dot/testdata
gonum.org/v1/gonum/graph/graphs
gonum.org/v1/gonum/graph/internal
gonum.org/v1/gonum/graph/path/internal
gonum.org/v1/gonum/graph/path/internal/testgraphs
gonum.org/v1/gonum/integrate/quad/internal
gonum.org/v1/gonum/internal
gonum.org/v1/gonum/internal/asm
gonum.org/v1/gonum/lapack
gonum.org/v1/gonum/lapack/internal
gonum.org/v1/gonum/lapack/internal/testdata
gonum.org/v1/gonum/lapack/internal/testdata/dlahr2test
gonum.org/v1/gonum/lapack/internal/testdata/dlaqr5test
gonum.org/v1/gonum/lapack/internal/testdata/dlasqtest
gonum.org/v1/gonum/lapack/internal/testdata/dsterftest
gonum.org/v1/gonum/lapack/internal/testdata/netlib
gonum.org/v1/gonum/lapack/testlapack
gonum.org/v1/gonum/lapack/testlapack/testdata
gonum.org/v1/gonum/mathext
gonum.org/v1/gonum/mathext/internal
gonum.org/v1/gonum/mathext/internal/amos
gonum.org/v1/gonum/mathext/internal/amos/amoslib
gonum.org/v1/gonum/mathext/internal/gonum
gonum.org/v1/gonum/optimize/convex
gonum.org/v1/gonum/optimize/convex/lp
gonum.org/v1/gonum/unit/autogen
```

These are either directories without go source or do not have proper package-level documentation.

**Comment by btracey** [comment]
What's your suggestion to get the rest of the packages with proper import paths?

**Comment by kortschak** [comment]
The majority of the paths there are not real misses. Some are packages that do not have and package doc and can have the canonical path added when that is done (these are mainly internal) and some are commands that in reality should be `// +build ignore` within the package they care for, or put into an internal/cmd/... file system.

In short, nothing in this PR.

**Comment by btracey** [comment]
I guess this is fine. I don't really like the half-state. but it makes sense to have one automatically done and then a second to fix the outstanding ones

Here is a list of the "real" ones for the next pr.
````
gonum.org/v1/gonum
gonum.org/v1/gonum/diff
gonum.org/v1/gonum/graph/encoding
gonum.org/v1/gonum/graph/ex
gonum.org/v1/gonum/graph/ex/fdpclust
gonum.org/v1/gonum/graph/formats
gonum.org/v1/gonum/graph/graphs
gonum.org/v1/gonum/lapack
gonum.org/v1/gonum/lapack/testlapack
gonum.org/v1/gonum/mathext
gonum.org/v1/gonum/optimize/convex
gonum.org/v1/gonum/optimize/convex/lp
gonum.org/v1/gonum/unit/autogen
````

It would be nice to have a doc.go in `gonum.org/v1/gonum`

**Comment by btracey** [comment]
LGTM

**Comment by kortschak** [comment]
Have a look through the paths, it's not really half done.

**Pull request merged**
