### PR TITLE
optimize: add Brent implementation

### PR DESCRIPTION
**Pull request by sbinet**
Please take a look.

### CODE REVIEW

**Comment by sbinet** [comment]
@chewxy, @btracey  could you have a look at this?
I've adapted (I think) what you had for the new `optimize` design.

but it seems there are a few things that aren't working...

**Comment by btracey** [comment]
Sorry for the delay. We didn't add this before because the discussion was that we should have a `root` package instead of putting the root-finding methods into optimize. There is some discussion on organization and design: https://github.com/gonum/gonum/issues/483

**Comment by vladimir-ch** [comment]
Why couldn't go this into optimize? Variants of the Brent's method can be used both for minimization and root finding of functions of one variable. What I'm not sure is whether this should implement `Method` or whether it should have its own entry function.

**Comment by btracey** [comment]
If it goes in here, I don't see why it should have its own entry function. Are there that many optimization algorithms that are specific to one-D that aren't root-finding algorithms? My experience is that the standard algorithms work pretty well in one-d (either local linesearch, or ListSearch, or some kind of global algorithm). It seems like if you want a bisection-like algorithm, it would be better to have those implemented in `root` and have a wrapper there which satisfies `optimize.Problem`.

**Comment by vladimir-ch** [comment]
I don't insist on Brent having its own entry function. The suggestion comes from the fact that `Method` was made for general n-dimensional problems while Brent works only for 1-dimensional problems. Perhaps a standalone function could offer a better and simpler API.

I'm confused about using an implementation of Brent in `root` for 1-d minimization. How would that work without differentiation?

**Comment by btracey** [comment]
Sorry, I meant to suggest that there could be a wrapper in either `root` or
`optimize` that takes a root-finding method and turns it into an
`optimize.Method`. You basically just shift one level of derivative
(Meaning, in `root` the user needs to supply Function and Gradient, the
wrapper would need Gradient and Hessian, which is fine in 1-d).

My main point is not wanting duplicate implementations of Bisection,
GoldenSearch, etc. in both `root` and `optimize` when the algorithms are
virtually identical, just one derivative shifted.

Both of the above points are orthogonal to the discussion of having a
second entry function for 1-D problems. I think we would only have to add a
new entry function and a new Problem type, so it's not very much API
surface. I'm not sure in gains very much though. Brent (for example) would
implement Method (in my hypothetical design), so it would have to check
it's not used for a multi-D function. I probably would still choose LBFGS
as a default method, so you don't gain that much there either. Seems like
the main benefit is a better matching Problem type. That could be enough
benefit to justify the API surface, unclear.

One idea is to have `root.Bounded` which is 1-d, and `root.Find` which is
many-D. We could use the same paradigm in optimize if we think it is worth
it, `optimize.Bounded` would be One-D. It would require passing a bound,
but we could enable methods to support inf, and so practically could
support unbounded choices.

**Comment by vladimir-ch** [comment]
About the wrapper: I understand what you mean but I'm still confused. How the "shift one level of derivative" part would be done? I can imagine going the other way around: in `root` take `f` and pass `|f|^2` to `optimize` in order to find the roots of `f` but even in that case I'm not convinced. I would just have two implementations, one in `root` and one in `optimize`.

About the second entry function for 1-d-only methods: it seems to me that having them all implement `Method` and checking that the dim is 1 is the best. Otherwise I'm afraid we would end up replicating `Method` and `Minimize` only this time with scalars instead of `[]float64`.

**Comment by vladimir-ch** [comment]
@sbinet Would you like to keep this open? I would eventually be able to take a look at it.

**Pull request closed without merging**
