### PR TITLE
interp: add not-a-knot cubic spline interpolator

### PR DESCRIPTION
**Pull request by romanwerpachowski**
Please take a look.

### CODE REVIEW

**Comment by romanwerpachowski** [comment]
How can I diagnose the build errors? It builds fine locally, and when I go to https://travis-ci.com/github/gonum/gonum/jobs/516634472 all I see in logs is "Automatic restarts limited: Please try restarting this job later or contact support@travis-ci.com."

**Comment by kortschak** [comment]
Don't worry about travis. I can do local arm64 builds if you want. We have nearly run out of build minutes there and they are not very responsive.

**Comment by romanwerpachowski** [comment]
Thanks. I think ARM will have the same FP precision as Intel so no need to adjust the tolerances for unit tests?

**Comment by kortschak** [comment]
I'll take a look. For the most part the precision is the same. The differences, when they happen, are in numerically unstable functions due to differences in operation ordering and the fact that the arm64 code generation emits FMA and FMS instructions when it can while the amd64 doesn't.

**Comment by kortschak** [comment]
All good.

```
TASK [Run tests on gonum.org/v1/gonum/interp in not-a-knot branch.] ************************************
changed: [bildr.fritz.box]

PLAY RECAP *********************************************************************************************
bildr.fritz.box            : ok=2    changed=2    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
```

**Comment by kortschak** [comment]
All good.

```
TASK [Run tests on gonum.org/v1/gonum/interp in not-a-knot branch.] ************************************
changed: [bildr.fritz.box]

PLAY RECAP *********************************************************************************************
bildr            : ok=2    changed=2    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
```

**Comment by romanwerpachowski** [comment]
Thanks!

**Comment by romanwerpachowski** [comment]
*ping*

**Review by vladimir-ch — APPROVED** [review]

**Pull request merged**
