### PR TITLE
Adding name to the CONTRIBUTORS and AUTHORS file

### PR DESCRIPTION
**Pull request by anirban6**
Please take a look.

### CODE REVIEW

**Comment by kortschak** [comment]
What was this for?

**Comment by anirban6** [comment]
Hello. I want to contribute to the integrate package, by incorporating some of the Newton Cotes formulas that I implemented in C back in the days when I was doing research. For a equally spaced lattice, Trapezoidal rule or even a Simpson can be improved upon with higher point formulae. Maybe I jumped the gun with this pull request, but it seemed like this was the suggested first step in https://github.com/gonum/gonum/blob/master/CONTRIBUTING.md

May I please be added so that I may contribute? Thank you.

**Comment by kortschak** [comment]
We don't have a CLA requirement, so you can start contributing whenever you want. The A+C addition happens after or with your first contribution.

**Comment by anirban6** [comment]
OK, I shall issue a separate pull request with my first contribution, and if that is accepted, please accept this one as well. Thanks.

**Comment by kortschak** [comment]
It is worth raising potential contributions on gonum-dev prior to submission, or raising a feature request issue here if the changes alter API.

**Comment by anirban6** [comment]
Will do. Thanks.

**Pull request closed without merging**
