### PR TITLE
blas/gonum: slice arguments to exact length

### LINKED ISSUE #733: blas/gonum: []float64 slices should be sliced to their shortest needed length
Currently we us s[n:] which matches the fortran. We are missing the opportunity for safety here by not saying s[n:m] where we know what m is.

### PR DESCRIPTION
**Pull request by vladimir-ch**
Also, avoid unnecessary use of ...To routines.

Please take a look.

### CODE REVIEW

**Comment by btracey** [comment]
We should really be slicing to the capacity though, right? Some of the lapack bugs come from missed out-of-bounds access, but they can also come from slicing beyond where it should be (this was at least the major problem I encountered with SVD)

**Comment by kortschak** [comment]
That's a good point. doing `s[:n:n]` would prevent reslicing back to an out-of-bound length.

**Comment by vladimir-ch** [comment]
Slicing to the capacity is too tedious, so I postpone it to a future PR. Can I merge if I remove the "Closes ..." clause?

**Comment by kortschak** [comment]
SGTM

**Pull request merged**
