### PR TITLE
Bump staticcheck to use go version from go.mod

### PR DESCRIPTION
**Pull request by khasanovbi**

### CODE REVIEW

**Review by kortschak — APPROVED** [review]
Thanks.

Can you send another PR with the commit message "A+C: add Bulat Khasanov", adding yourself to AUTHORS and CONTRIBUTORS. When that's done, I'll merge this.

**Comment by kortschak** [comment]
The A+C should be a separate PR. I need to edit the commit message on this PR for the staticcheck change and GitHub will not allow that while retaining the distinct commits.

**Review by kortschak — APPROVED** [review]

**Comment by khasanovbi** [comment]
> The A+C should be a separate PR.

Sorry my mistake, created another PR https://github.com/gonum/gonum/pull/1869

**Comment by kortschak** [comment]
Thanks

**Pull request merged**
