### PR TITLE
path: use node ID in dominator tree for node retrieval

### PR DESCRIPTION
**Pull request by mewmew**
Updates #31.

Please take a look.

### CODE REVIEW

**Comment by kortschak** [comment]
Probably we should have some tests here?

**Comment by mewmew** [comment]
The dom tree has test cases in `control_flow_test.go`. It uses reflect instead of directly invoking `DominatorOf` and `DominatedBy` it seems.

**Comment by kortschak** [comment]
Yeah, I saw that. The accessors are pretty simple, but it would be good to have something that ensures we're being honest in the future.

Replace what exists with this
```
			for q, want := range test.want.dominatorOf {
				node := got.DominatorOf(q)
				if node != want {
					t.Errorf("unexpected dominator tree result from %s dominated of %v: got:%v want:%v",
						alg.name, q, node, want)
				}
			}

			for _, nodes := range got.dominatedBy {
				sort.Sort(ordered.ByID(nodes))
			}
			for q, want := range test.want.dominatedBy {
				nodes := got.DominatedBy(q)
				if !reflect.DeepEqual(nodes, want) {
					t.Errorf("unexpected dominator tree result from %s dominated by %v: got:%v want:%v",
						alg.name, q, nodes, want)
				}
			}
```

**Comment by mewmew** [comment]
> Replace what exists with this

Thanks! I update the test case with the code you wrote.

**Comment by kortschak** [comment]
I should have left the tree comparison in in addition to the new tests; now we confirm that the result we see is a subset of the expectation, but don't confirm that it's not a proper superset. I'll send a fix.

**Comment by mewmew** [comment]
> I should have left the tree comparison in in addition to the new tests; now we confirm that the result we see is a subset of the expectation, but don't confirm that it's not a proper superset. I'll send a fix.

Yeah, that's better. Thanks for submitting the PR.

**Pull request merged**
