### PR TITLE
stat: add matrix conditioning functions for MCA and MDS

### PR DESCRIPTION
**Pull request by kortschak**
DO NOT SUBMIT

See https://groups.google.com/d/topic/gonum-dev/gEiEWpCDssU/discussion

### CODE REVIEW

**Comment by btracey** [comment]
I think this idea looks good. I don't know if there's a better place for this to be than stat, I'm not sure there's a class of these transformations that works for many algorithms (though I can try and read more about this if you'd like). If this is a more general transformation approach, we could consider putting it into a sub-package. 

I don't like the name "ClassicalScaling" , it's pretty general for a specific idea. I'd vote TorgersonScaling as it's immediately googleable and clearly some kind of specific algorithm. I'd also side to TransformDisjunctive for similar reasons, more clearly legible to someone who isn't already familiar.

**Comment by kortschak** [comment]
Agreed on the naming. I'm somewhat confused about the behaviour though. From my reading the Togerson scaling should just work as an MDS by doing a PCA, but it doesn't seem to here (it disagrees with R's MDS).

**Comment by kortschak** [comment]
I think maybe there should be an MDS package, "gonum.org/v1/gonum/stat/mds", since there are too may types of this.

**Comment by kortschak** [comment]
OK, I think I misunderstood what people were saying about Torgerson Scaling. I have fixed that, but it no longer fits in this PR (though I'll park it here for a while until we decide what to do). I suspect it should go in the above mentioned mds package, and the `TransformDisjunctive` should go here, though I'm still waiting on input from the original requester (I don't see any way to summon him here).

**Comment by kortschak** [comment]
OK. I'm going to abandon this and open two PRs for the MCA in stat and for TCS in stat/mds.

**Pull request closed without merging**
