### PR TITLE
travis: fix build

### PR DESCRIPTION
**Pull request by kortschak**
* Add completish set of tests (from "github.com/gonum/matrix").
* Fix single failure.

@btracey Please take a look.

### CODE REVIEW

**Comment by btracey** [comment]
LGTM

**Comment by kortschak** [comment]
We get three failures here for noasm/appengine.

- stat principle component analysis — error in lowest valued column
- lapack/native Dgeev — unexpected eigenvalues
- lapack/native Dgebrd — a, d, e and tauQ mismatches

I can skip those tests for noasm/appengine in the interim.

**Comment by btracey** [comment]
Okay to skip until we can improve tests.

**Comment by kortschak** [comment]
There is one set of codegen that is not checked - the dot parser (#24).

**Pull request merged**
