### PR TITLE
CONDUCT: add a CONDUCT document

### PR DESCRIPTION
**Pull request by kortschak**
This merely exists to make sure automated tools (for example [here](https://github.com/gonum/gonum/community)) and cursory glances of the repo see that we care about this kind of thing.

I have retained the optimistic name and refrained from using the prescriptive term "Code".

This needs a quorum of approvers. I don't know how big.

Please take a look.

### CODE REVIEW

**Comment by btracey** [comment]
I think it's important we add the sentiment that we are open and affirming.

`The Gonum project welcomes contributions from all, regardless of background and identity. Contributors should find themselves in an open and welcoming environment. When contributing or otherwise participating ...`

**Comment by kortschak** [comment]
"The Gonum project welcomes contributions from all. Contributors should foster an open and welcoming environment. When contributing or otherwise participating ..."?

**Comment by btracey** [comment]
SGTM

**Comment by kortschak** [comment]
PTAL

**Comment by kortschak** [comment]
I'll leave this until the end of the month to give others time to comment. After that I'll merge.

/cc @Kunde21 @mewmew @ctessum

**Pull request merged**
