### PR TITLE
graph/coloring: allow warm start for DsaturExact

### PR DESCRIPTION
**Pull request by kortschak**
This is a replay of #1705, now onto the merged coloring package. I had originally intended to wait until I had improved the base performance of the `DsaturExact` implementation before I applied this change, but I suspect that I won't have time to address that for a while (my initial investigations suggest that it's both subtle and extensive to improve the way that the color accounting is currently done), so rather than wait with a poorly performing exact coloring implementation I think this should go in, and the work to formally examine the impact of this change can happen after the base improvements are made with minor alterations of code added here.

The algorithmic addition is quite straightforward and I think the implications on run time are reasonably clear. I have some rough notes that I prepared a while back that I can make available to explain the behaviour (OOB since they are not public quality yet).

Please take a look.

### CODE REVIEW

**Review by vladimir-ch — APPROVED** [review]

**Comment by kortschak** [comment]
Here are the benchmarks. It looks horrifying until you look at the larger queens cases, and the sudoku problem. The variance on the times is very high due to the high impact of search path that is chosen, and the fact that it is partially randomly chosen.

<table class='benchstat oldnew'>
<tr class='configs'><th><th>old.bench<th>new.bench
<tbody>
<tr><th><th colspan='2' class='metric'>time/op<th>delta
<tr class='better'><td>Coloring/empty/DsaturExact-8<td>6.67ns ± 2%<td>6.01ns ± 1%<td class='delta'>−9.91%<td class='note'>(p=0.000 n=10&#43;9)
<tr class='worse'><td>Coloring/singleton/DsaturExact-8<td>1.16µs ± 1%<td>2.11µs ± 6%<td class='delta'>&#43;81.59%<td class='note'>(p=0.000 n=9&#43;10)
<tr class='worse'><td>Coloring/kite/DsaturExact-8<td>24.6µs ± 1%<td>43.6µs ± 5%<td class='delta'>&#43;76.92%<td class='note'>(p=0.000 n=10&#43;9)
<tr class='worse'><td>Coloring/triangle&#43;1/DsaturExact-8<td>14.6µs ± 1%<td>23.9µs ± 3%<td class='delta'>&#43;63.97%<td class='note'>(p=0.000 n=10&#43;9)
<tr class='worse'><td>Coloring/bipartite_halves/DsaturExact-8<td>48.1µs ± 1%<td>76.4µs ± 2%<td class='delta'>&#43;58.94%<td class='note'>(p=0.000 n=10&#43;10)
<tr class='worse'><td>Coloring/bipartite_alternating/DsaturExact-8<td>48.1µs ± 1%<td>76.3µs ± 1%<td class='delta'>&#43;58.66%<td class='note'>(p=0.000 n=10&#43;9)
<tr class='worse'><td>Coloring/cubical/DsaturExact-8<td>47.9µs ± 2%<td>77.7µs ± 3%<td class='delta'>&#43;62.08%<td class='note'>(p=0.000 n=9&#43;9)
<tr class='worse'><td>Coloring/HoG33106/DsaturExact-8<td>107µs ± 1%<td>175µs ± 7%<td class='delta'>&#43;62.49%<td class='note'>(p=0.000 n=9&#43;10)
<tr class='worse'><td>Coloring/HoG41237/DsaturExact-8<td>323ms ± 2%<td>330ms ± 1%<td class='delta'>&#43;2.11%<td class='note'>(p=0.002 n=9&#43;8)
<tr class='worse'><td>Coloring/exams/DsaturExact-8<td>37.2µs ± 1%<td>62.9µs ± 2%<td class='delta'>&#43;69.12%<td class='note'>(p=0.000 n=9&#43;10)
<tr class='worse'><td>Coloring/exam_scheduler_1/DsaturExact-8<td>135µs ± 1%<td>275µs ±52%<td class='delta'>&#43;103.38%<td class='note'>(p=0.000 n=9&#43;10)
<tr class='worse'><td>Coloring/exam_scheduler_2/DsaturExact-8<td>67.3µs ± 2%<td>114.5µs ± 2%<td class='delta'>&#43;70.21%<td class='note'>(p=0.000 n=10&#43;9)
<tr class='worse'><td>Coloring/Brélaz/DsaturExact-8<td>84.9µs ± 2%<td>137.8µs ± 2%<td class='delta'>&#43;62.38%<td class='note'>(p=0.000 n=10&#43;9)
<tr class='worse'><td>Coloring/Lima_Carmo/DsaturExact-8<td>46.9µs ± 1%<td>76.8µs ± 2%<td class='delta'>&#43;63.88%<td class='note'>(p=0.000 n=8&#43;9)
<tr class='worse'><td>Coloring/San_Segundo/DsaturExact-8<td>193µs ± 4%<td>259µs ± 2%<td class='delta'>&#43;33.99%<td class='note'>(p=0.000 n=8&#43;10)
<tr class='worse'><td>Coloring/tetrahedron/DsaturExact-8<td>17.1µs ± 2%<td>33.5µs ± 4%<td class='delta'>&#43;96.48%<td class='note'>(p=0.000 n=9&#43;9)
<tr class='worse'><td>Coloring/triangle/DsaturExact-8<td>9.39µs ± 1%<td>18.61µs ± 9%<td class='delta'>&#43;98.21%<td class='note'>(p=0.000 n=9&#43;9)
<tr class='worse'><td>Coloring/square/DsaturExact-8<td>16.0µs ± 2%<td>26.1µs ± 2%<td class='delta'>&#43;63.17%<td class='note'>(p=0.000 n=10&#43;9)
<tr class='worse'><td>Coloring/cycle-5/DsaturExact-8<td>32.1µs ± 2%<td>44.2µs ± 1%<td class='delta'>&#43;37.85%<td class='note'>(p=0.000 n=10&#43;9)
<tr class='worse'><td>Coloring/cycle-6/DsaturExact-8<td>26.4µs ± 2%<td>43.1µs ± 1%<td class='delta'>&#43;63.21%<td class='note'>(p=0.000 n=10&#43;8)
<tr class='worse'><td>Coloring/wheel-5/DsaturExact-8<td>31.4µs ± 2%<td>54.4µs ± 2%<td class='delta'>&#43;73.39%<td class='note'>(p=0.000 n=10&#43;10)
<tr class='worse'><td>Coloring/wheel-6/DsaturExact-8<td>59.9µs ± 2%<td>86.9µs ± 1%<td class='delta'>&#43;45.14%<td class='note'>(p=0.000 n=10&#43;10)
<tr class='worse'><td>Coloring/wheel-7/DsaturExact-8<td>53.8µs ± 1%<td>91.5µs ± 1%<td class='delta'>&#43;69.94%<td class='note'>(p=0.000 n=10&#43;9)
<tr class='worse'><td>Coloring/sudoku_board/DsaturExact-8<td>87.4ms ± 2%<td>135.5ms ± 1%<td class='delta'>&#43;54.96%<td class='note'>(p=0.000 n=10&#43;9)
<tr class='unchanged'><td>Coloring/sudoku_problem/DsaturExact-8<td>10.3s ±68%<td>7.3s ±130%<td class='nodelta'>~<td class='note'>(p=0.165 n=10&#43;10)
<tr class='worse'><td>Coloring/cs_shc/DsaturExact-8<td>28.1µs ± 2%<td>48.9µs ± 4%<td class='delta'>&#43;73.64%<td class='note'>(p=0.000 n=10&#43;9)
<tr class='worse'><td>Coloring/gis_hc/DsaturExact-8<td>24.3µs ± 2%<td>43.1µs ± 8%<td class='delta'>&#43;77.27%<td class='note'>(p=0.000 n=9&#43;10)
<tr class='worse'><td>Coloring/gis_shc|rs_shc/DsaturExact-8<td>14.2µs ± 2%<td>24.1µs ±11%<td class='delta'>&#43;69.96%<td class='note'>(p=0.000 n=9&#43;10)
<tr class='worse'><td>Coloring/lf_hc/DsaturExact-8<td>44.8µs ± 2%<td>75.3µs ± 1%<td class='delta'>&#43;67.95%<td class='note'>(p=0.000 n=8&#43;9)
<tr class='worse'><td>Coloring/lf_shc/DsaturExact-8<td>24.6µs ± 1%<td>40.3µs ± 2%<td class='delta'>&#43;64.18%<td class='note'>(p=0.000 n=8&#43;9)
<tr class='worse'><td>Coloring/lfi_hc/DsaturExact-8<td>146µs ± 2%<td>160µs ± 1%<td class='delta'>&#43;9.47%<td class='note'>(p=0.000 n=10&#43;9)
<tr class='worse'><td>Coloring/lfi_shc|slf_shc/DsaturExact-8<td>87.0µs ± 1%<td>90.0µs ± 1%<td class='delta'>&#43;3.50%<td class='note'>(p=0.000 n=10&#43;10)
<tr class='worse'><td>Coloring/no_solo/DsaturExact-8<td>82.8µs ± 1%<td>127.2µs ± 2%<td class='delta'>&#43;53.63%<td class='note'>(p=0.000 n=9&#43;10)
<tr class='worse'><td>Coloring/sl_hc/DsaturExact-8<td>122µs ± 2%<td>169µs ± 3%<td class='delta'>&#43;38.09%<td class='note'>(p=0.000 n=10&#43;10)
<tr class='worse'><td>Coloring/sl_shc/DsaturExact-8<td>35.3µs ± 1%<td>59.5µs ± 2%<td class='delta'>&#43;68.70%<td class='note'>(p=0.000 n=10&#43;10)
<tr class='worse'><td>Coloring/slf_hc/DsaturExact-8<td>103µs ± 2%<td>115µs ± 2%<td class='delta'>&#43;11.79%<td class='note'>(p=0.000 n=10&#43;9)
<tr class='worse'><td>Coloring/sli_hc/DsaturExact-8<td>195µs ± 2%<td>271µs ± 1%<td class='delta'>&#43;39.40%<td class='note'>(p=0.000 n=10&#43;9)
<tr class='worse'><td>Coloring/sli_shc/DsaturExact-8<td>43.6µs ± 1%<td>72.6µs ± 1%<td class='delta'>&#43;66.72%<td class='note'>(p=0.000 n=9&#43;9)
<tr class='worse'><td>Coloring/rsi_shc/DsaturExact-8<td>32.7µs ± 1%<td>55.2µs ± 1%<td class='delta'>&#43;68.63%<td class='note'>(p=0.000 n=10&#43;9)
<tr class='worse'><td>Coloring/V_plus_not_in_A_cal/DsaturExact-8<td>48.8µs ± 1%<td>77.6µs ± 2%<td class='delta'>&#43;59.02%<td class='note'>(p=0.000 n=10&#43;10)
<tr class='worse'><td>Coloring/queen5_5/DsaturExact-8<td>2.72ms ± 2%<td>4.80ms ± 1%<td class='delta'>&#43;76.24%<td class='note'>(p=0.000 n=10&#43;9)
<tr class='better'><td>Coloring/queen6_6/DsaturExact-8<td>676ms ±34%<td>276ms ±44%<td class='delta'>−59.17%<td class='note'>(p=0.000 n=10&#43;9)
<tr class='better'><td>Coloring/queen7_7/DsaturExact-8<td>4.09s ±87%<td>1.55s ±116%<td class='delta'>−62.00%<td class='note'>(p=0.022 n=9&#43;10)
</tbody>
</table>

**Comment by vladimir-ch** [comment]
Almost all the other benchmarks are in the order of (tens of) µs, so I would put more weight on the larger problems where the warm up pay off. Are there other (generated) larger benchmark problems that we could add?

**Comment by kortschak** [comment]
There are a bunch from where I got the queens graphs. Note that queens-8-8 takes a very long time with this implementation (either old or new) due to allocation inefficiency that I want to fix. I'm not particular fussed to add more bench marks. I think the result is sound.

**Comment by vladimir-ch** [comment]
Agreed.

**Pull request merged**
