### PR TITLE
modules,graph/layout: update for gonum/plot v0.9.0

### PR DESCRIPTION
**Pull request by kortschak**
Please take a look.

### CODE REVIEW

**Review by sbinet — COMMENTED** [review]
LGTM.

all the `xyz_isomap_<GOARCH>_golden.png` files could probably be removed (and make use of `cmpimg` "approx" equal.

(but those could be done in a later PR, possibly after `v0.9.0`)

**Comment by kortschak** [comment]
Can I have a formal approval?

**Review by sbinet — APPROVED** [review]
LGTM.

(apologies for the fat fingers)

**Comment by kortschak** [comment]
> all the xyz_isomap_<GOARCH>_golden.png files could probably be removed (and make use of cmpimg "approx" equal.

Unfortunately this is not likely to ever be possible; different architectures can have completely different layouts.

**Pull request merged**
