### PR TITLE
graph: move NewEdge method from encoding.Builder to graph.EdgeAdder

### LINKED ISSUE #56: graph/encoding/dot: NewEdge method of Builder is troubling
@mewmew I'm troubled by the presence of the NewEdge method in the Builder interface. I can see why it's there, but it is almost the same as SetEdge, and that's a problem. Possibly it could go away in the changes associated with the fix to #31?

### PR DESCRIPTION
**Pull request by mewmew**
Also rename graph.EdgeSetter to graph.EdgeAdder.

Fixes #56.

### CODE REVIEW

**Comment by kortschak** [comment]
Sorry. I am just looking at using the new API in gen, and it seems that `NewEdge` should take a weight parameter, since it is not possible to set weight otherwise (without excursion from the API).

**Comment by kortschak** [comment]
What is your view on the addition of a weight parameter here? At the moment, edge weights are first class, so it should go in, but depending on the outcome of thinking in #201, we could conceivably remove it later.

**Comment by mewmew** [comment]
> What is your view on the addition of a weight parameter here? At the moment, edge weights are first class, so it should go in, but depending on the outcome of thinking in #201, we could conceivably remove it later.

I think there is no rush to merge this PR. It is a disruptive change, so lets get it right from the start. Lets continue discussions in #203 until we reach consensus, and keep this PR and #201 on hold for now.

**Comment by mewmew** [comment]
Ok, merging.

**Pull request merged**
