### PR TITLE
README: fix broken link to most recent Go releases

### PR DESCRIPTION
**Pull request by empire**
Please take a look.

### CODE REVIEW

**Review by romanwerpachowski — APPROVED** [review]
Thanks!

**Comment by kortschak** [comment]
Thanks. Please add a commit or file another PR adding yourself to AUTHORS and CONTRIBUTORS with the commit message "A+C: add Hossein Zolfi".

**Comment by empire** [comment]
@kortschak thanks, done.

**Review by kortschak — APPROVED** [review]
Thanks

**Pull request merged**
