### PR TITLE
travis: add go-1.10.x

### PR DESCRIPTION
**Pull request by kortschak**
Please take a look.

### CODE REVIEW

**Comment by kortschak** [comment]
Note that 1.10 is not properly tested because of https://github.com/travis-ci/gimme/issues/132.

**Comment by btracey** [comment]
Is the suggestion we merge it like this, or wait until the issue is resolved?

**Comment by kortschak** [comment]
I'd prefer to wait.

**Comment by btracey** [comment]
I agree.

**Comment by kortschak** [comment]
Approvals are fine though. Then I can merge when the travis issue is resolved.

**Comment by kortschak** [comment]
Travis' gimme is fixed. Retesting on go1.10.

**Pull request merged**
